### ISSUE TITLE
don't have a turn/stun server

### ISSUE THREAD

**Issue by haormj** [BenjaminFaal/apprtc-docker#1]
I pull your docker images,when I run it and access localhost:8080
tell me don't have turn server,so I read you shell and find three env params,but I don't konw how to config them.

**Comment by BenjaminFaal** [comment]
Hello you need to specify the arguments when you run the docker, otherwise you can try something like: https://kitematic.com/ which will help you configuring

**Comment by haormj** [comment]
get it,thinks!
